name: CrateReloaded
main: com.hazebyte.crate.cratereloaded.CorePlugin
version: ${project.version}
authors: [dinosaur, RebornIV]
website: crate.hazebyte.com
depend:
softdepend: [Essentials, Vault, Holograms, Citizens, Multiverse-Core, PlaceholderAPI, CMI, DecentHolograms]
api-version: 26.1